import { defineConfig } from "vitest/config"
import tsconfigPaths from "vite-tsconfig-paths"

export default defineConfig({
  plugins: [tsconfigPaths({ projects: ["./tsconfig.json"] })],
  test: {
    environment: "node",
    globals: true,
    setupFiles: ["src/test/setup.ts"],
    include: [
      "src/**/*.test.{ts,tsx}",
      "maintenance/**/*.test.ts",
      "functions/**/*.test.{ts,js}",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "text", "json"],
      include: ["src/**", "functions/**"],
      exclude: [
        // Generated by tanstack/router-plugin
        "src/routeTree.gen.ts",
        // Generated by kysely-codegen
        "src/db/types.ts",
        // Type-only file, no executable code
        "src/lib/types.ts",
        // Module-state populated by initDatabase (WASM fetch); helpers untestable without it
        "src/lib/database.ts",
        // Branches on import.meta.env.SSR: one side is a build-time virtual
        // module, the other is the WASM database. Neither exists under vitest.
        "src/lib/fishData.ts",
        // Fetches WASM SQLite over HTTP at runtime — not testable in node
        "src/lib/DatabaseContext.tsx",
        // WASM init wrapper around @sqlite.org/sqlite-wasm — not testable in node
        "src/db/sqlite-wasm-dialect.ts",
        // Embla-carousel-react wrapper requiring browser APIs (ResizeObserver, etc.)
        "src/components/ui/carousel.tsx",
        // Wires devtools, theme init script, providers — mostly app shell setup
        "src/routes/__root.tsx",
        // Static page, framework-coupled via createFileRoute
        "src/routes/about.tsx",
        // File-route definitions; tested via route loaders requires full router setup
        "src/routes/index.tsx",
        "src/routes/name.$id.tsx",
        "src/routes/species.$id.tsx",
        // Test infra
        "src/test/**",
        // Tests themselves
        "**/*.test.{ts,tsx}",
        // Runs in Cloudflare Workers runtime, hard to test in node
        "functions/_middleware.ts",
        // Runs in Cloudflare Workers runtime (OG image renderer)
        "functions/og/**",
      ],
      thresholds: {
        lines: 90,
        // Branches relaxed to 85 due to small-file artifacts: cva default-param
        // branches in button/input (50% on a 4-branch file = 1 missing) and
        // similar default-fallback branches in router/queryClient/utils that
        // our tests can't reach. Files >50 LOC consistently sit above 85%.
        branches: 85,
        functions: 90,
        statements: 90,
      },
    },
  },
})
