name = "linkedfin-net"
pages_build_output_dir = "dist/client"
compatibility_date = "2024-09-23"

[build]
command = "pnpm install --frozen-lockfile && pnpm rebuild better-sqlite3 && pnpm check && pnpm tsc --noEmit && pnpm test && pnpm db:validate && pnpm build"

[build.environment]
SKIP_DEPENDENCY_INSTALL = "true"

[[routes]]
pattern = "linkedfin.net"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "linkedfin-db"
database_id = "f50422f5-91d9-483f-b2d5-dd693bdc775b"
