/**
 * Build-time OG metadata generator.
 *
 * Reads fish.db with better-sqlite3 and writes functions/og-data.ts
 * containing static lookup tables used by the Pages Functions middleware
 * and OG image endpoint — replacing the runtime D1 dependency.
 *
 * Run: pnpm og:generate
 */

import Database from "better-sqlite3";
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const DB_PATH = resolve(import.meta.dirname, "../../fish.db");
const OUT_PATH = resolve(import.meta.dirname, "../../functions/og-data.ts");

const db = new Database(DB_PATH, { readonly: true });

interface NameRow {
	id: string;
	name: string;
	lang: string;
	etymology: string | null;
	transliteration: string | null;
	region_name: string;
}

interface SpeciesRow {
	id: string;
	scientific_name: string;
}

interface NameSpeciesRow {
	species_id: string;
	name: string;
}

const names: NameRow[] = db
	.prepare(
		"SELECT n.id, n.name, n.lang, n.etymology, n.transliteration, r.name as region_name FROM names n JOIN regions r ON n.region_id = r.id",
	)
	.all() as NameRow[];

const species: SpeciesRow[] = db
	.prepare("SELECT id, scientific_name FROM species")
	.all() as SpeciesRow[];

const namesBySpecies: NameSpeciesRow[] = db
	.prepare("SELECT species_id, name FROM names ORDER BY id")
	.all() as NameSpeciesRow[];

db.close();

// Build namesBySpeciesId grouped map
const namesBySpeciesId: Record<string, string[]> = {};
for (const row of namesBySpecies) {
	if (!namesBySpeciesId[row.species_id]) {
		namesBySpeciesId[row.species_id] = [];
	}
	namesBySpeciesId[row.species_id].push(row.name);
}

function esc(s: string | null): string {
	if (s === null) return "null";
	return JSON.stringify(s);
}

const lines: string[] = [
	"// Auto-generated by maintenance/scripts/og-data-gen.ts — do not edit",
	"",
	"export const namesById: Record<",
	"\tstring,",
	"\t{",
	"\t\tname: string;",
	"\t\tlang: string;",
	"\t\tetymology: string | null;",
	"\t\ttransliteration: string | null;",
	"\t\tregion_name: string;",
	"\t}",
	"> = {",
];

for (const n of names) {
	lines.push(
		`\t${esc(n.id)}: { name: ${esc(n.name)}, lang: ${esc(n.lang)}, etymology: ${esc(n.etymology)}, transliteration: ${esc(n.transliteration)}, region_name: ${esc(n.region_name)} },`,
	);
}
lines.push("};", "");

lines.push(
	"export const speciesById: Record<string, { scientific_name: string }> = {",
);
for (const s of species) {
	lines.push(
		`\t${esc(s.id)}: { scientific_name: ${esc(s.scientific_name)} },`,
	);
}
lines.push("};", "");

lines.push(
	"export const namesBySpeciesId: Record<string, string[]> = {",
);
for (const [id, nameList] of Object.entries(namesBySpeciesId)) {
	lines.push(`\t${esc(id)}: ${JSON.stringify(nameList)},`);
}
lines.push("};", "");

writeFileSync(OUT_PATH, `${lines.join("\n")}\n`);
execSync(`npx biome format --write ${OUT_PATH}`, { stdio: "inherit" });
console.log(`Generated ${OUT_PATH} (${names.length} names, ${species.length} species)`);
